version: '2.1'
orbs:
  python: circleci/python@2.0.3

jobs:
  build:
    executor:
      name: python/default
      tag: "3.9"

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: poetry

      - run:
          name: Install Sharpdev
          command: |
            wget https://github.com/Sharpz7/sharpdev/releases/download/1.6/linux.tar.gz
            sudo tar -C /usr/local/bin/ -zxvf linux.tar.gz
            rm -r linux.tar.gz
            chmod u+x /usr/local/bin/sharpdev

      - run:
          name: Lint
          command: |
            sharpdev lint

      - run:
          name:
          command: |
            sharpdev unit

workflows:
  main:
    jobs:
      - build