version: 2.1

jobs:
  build_and_test:
    docker:
      - image: python:3.9

    steps:
      - checkout

      - run:
          name: Install Tox and Poetry
          command: |
            pip install tox poetry
            poetry install

      - run:
          name: Run Lint
          command: tox -e format-code

      - run:
          name: Run Unit Tests
          command: tox -e py39

workflows:
  sharprocket:
    jobs:
      - build_and_test