version: '2.1'
orbs:
  python: circleci/python@2.0.3

jobs:
  build:
    executor:
      name: python/default
      tag: "3.9"

    steps:
      - checkout

      - run:
          name: Install Tox
          command: |
            pip install tox


      - python/install-packages:
          pkg-manager: poetry

      - run:
          name: Lint
          command: |
            poetry run tox -e format-code

      - run:
          name: Test
          command: |
            tox -e py39


workflows:
  main:
    jobs:
      - build