version: '2.1'
orbs:
  python: circleci/python@2.0.3
  sharpdev: sharptools/sharpdev@volatile

jobs:
  build:
    executor:
      name: python/default
      tag: "3.9"

    steps:
      - checkout

      - sharpdev/install

      - python/install-packages:
          pkg-manager: poetry

      - run:
          name: Lint
          command: |
            sharpdev lint

      - run:
          name: Unit Tests
          command: |
            sharpdev unit

workflows:
  main:
    jobs:
      - build